name: CI

on: 
  push:
    branches:
      - main
    
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo #--minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.TOKEN }}
          # external_repository: GabrielGarcia-Serrano/GabrielGarcia-Serrano.github.io
          publish_dir: ./public
          #   keep_files: true
          # publish_branch: master
        #   cname: example.com